sudo: required

language: go

go:
  - 1.6

node_js:
  - 5

services:
  - docker

script:
  - make build-linux
  - make package

install:
  - go get github.com/mattermost/platform/api
  - go get github.com/mattermost/platform/einterfaces
  - go get github.com/mattermost/platform/manualtesting
  - go get github.com/mattermost/platform/model
  - go get github.com/mattermost/platform/store
  - go get github.com/mattermost/platform/utils
  - go get github.com/mattermost/platform/web
